
buildscript {
    ext.kotlin_version = '2.0.21' // Specify the Kotlin version
    repositories {
        google()
        mavenCentral()
    }
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:-options"
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.android.tools.build:gradle:8.5.2' // Ensure the AGP matches Kotlin
    }
}


allprojects {
    repositories {
        google()
        mavenCentral()
    }

}



// Set a common build directory for all modules
rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

// Define a "clean" task

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
